language: elixir

elixir:
  - 1.2.5

otp_release:
  - 18.2.1

env:
  - MIX_ENV=test

script:
  - mix deps.get
  - mix credo --only warning
  - mix test
  - mix coveralls.travis

after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
