language: elixir

elixir:
  - 1.2.2

otp_release:
  - 18.2.1

env:
  - MIX_ENV=test

script:
  - mix do deps.get, credo, test
  - mix compile
  - mix coveralls.travis

after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
